server:
   port: 8888
spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
       git:    
         uri: https://github.com/vakshay8/microservices
         skipSslValidation: true       
         
    